package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */

import com.jetbrains.teamsys.database.Entity;

public abstract class EntityAdapter<T extends Entity> implements IEntityListener<T> {
  public void updatedSync(T old, T current) {
  }

  public void updatedAsync(T old, T current) {
  }

  public void addedSync(T added) {
  }

  public void addedAsync(T added) {
  }

  public void removedSyncBeforeFlush(T removed) {
  }

  public void removedSync(T removed) {
  }

  public void removedAsync(T removed) {
  }
}
