package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */

import jetbrains.exodus.core.execution.DelegatingJobProcessor;
import jetbrains.exodus.core.execution.ThreadJobProcessor;

public class EventsMultiplexerJobProcessor {
  public static DelegatingJobProcessor<ThreadJobProcessor> getInstance() {
    return EventsMultiplexer.getInstance().getAsyncJobProcessor();
  }
}
