package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */

import com.jetbrains.teamsys.core.execution.DelegatingJobProcessor;
import com.jetbrains.teamsys.core.execution.ThreadJobProcessor;
import com.jetbrains.teamsys.core.execution.ThreadJobProcessorPool;

public class EventsMultiplexerJobProcessor extends DelegatingJobProcessor<ThreadJobProcessor> {
  private static EventsMultiplexerJobProcessor instance = new EventsMultiplexerJobProcessor();

  private EventsMultiplexerJobProcessor() {
    super(ThreadJobProcessorPool.getOrCreateJobProcessor("EventsMultiplexerJobProcessor"));
    this.setExceptionHandler(new ExceptionHandlerImpl());
    this.start();
  }

  public static EventsMultiplexerJobProcessor getInstance() {
    return instance;
  }
}
