package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */

import com.jetbrains.teamsys.core.execution.JobProcessorExceptionHandler;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import com.jetbrains.teamsys.core.execution.JobProcessor;
import com.jetbrains.teamsys.core.execution.Job;

public class ExceptionHandlerImpl implements JobProcessorExceptionHandler {
  protected static Log log = LogFactory.getLog(ExceptionHandlerImpl.class);

  public ExceptionHandlerImpl() {
  }

  public void handle(JobProcessor p, Job j, Throwable e) {
    if (log.isErrorEnabled()) {
      log.error("Exception inside job processor [" + p + "] while executing job [" + j + "]", e);
    }
  }
}
