package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */

import com.jetbrains.teamsys.database.Entity;

public interface IEntityListener<T extends Entity> {
  public void addedAsync(T added);
  public void addedSync(T added);
  public void updatedAsync(T old, T current);
  public void updatedSync(T old, T current);
  public void removedSyncBeforeFlush(T removed);
  public void removedSync(T removed);
  public void removedAsync(T removed);
}
