package jetbrains.teamsys.dnq.runtime.events;

/*Generated by MPS */


/*package*/ enum Where {

  @Deprecated
  SYNC_BEFORE_FLUSH(),
  SYNC_BEFORE_CONSTRAINTS(),
  SYNC_AFTER_FLUSH(),
  ASYNC_AFTER_FLUSH();

  Where() {
  }
}
