/**
 * Copyright 2006 - 2026 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jetbrains.exodus.entitystore.youtrackdb.query

import com.google.common.truth.Truth.assertThat
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID
import jetbrains.exodus.Questionable
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinBlock
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinBlock.*
import jetbrains.exodus.entitystore.youtrackdb.gremlin.asYT
import org.apache.tinkerpop.gremlin.process.traversal.translator.GroovyTranslator
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__ as Anon
import org.junit.Test

/**
 * Tests that each GremlinBlock produces the expected Gremlin traversal.
 * This is the Gremlin-based analog of YTDBQueryTest from the graph-store branch,
 * which asserted the SQL strings generated by the SQL query builder.
 * Here we use GroovyTranslator to render the traversal bytecode as readable
 * Gremlin/Groovy strings and assert them.
 */
class GremlinQueryTest {

    private val translator = GroovyTranslator.of("__")

    private fun GremlinBlock.toGremlin(): String =
        translator.translate(traverse(Anon.start<Any>().asYT()).asAdmin().bytecode).script

    @Test
    fun `All produces empty traversal`() {
        assertThat(All.toGremlin()).isEqualTo("__")
    }

    @Test
    fun `None produces discard`() {
        assertThat(None.toGremlin()).isEqualTo("__.discard()")
    }

    @Test
    fun `PropEqual produces has with value`() {
        assertThat(PropEqual("name", "John").toGremlin())
            .isEqualTo("""__.has("name","John")""")
    }

    @Test
    fun `PropNull produces hasNot`() {
        assertThat(PropNull("name").toGremlin())
            .isEqualTo("""__.hasNot("name")""")
    }

    @Test
    fun `PropNotNull produces has without value`() {
        assertThat(PropNotNull("prop").toGremlin())
            .isEqualTo("""__.has("prop")""")
    }

    @Test
    fun `Or produces or with two sub-traversals`() {
        assertThat(Or(PropEqual("name", "a"), PropEqual("name", "b")).toGremlin())
            .isEqualTo("""__.or(__.has("name","a"),__.has("name","b"))""")
    }

    @Test
    fun `And produces and with two sub-traversals`() {
        assertThat(And(PropEqual("name", "a"), PropEqual("x", "b")).toGremlin())
            .isEqualTo("""__.and(__.has("name","a"),__.has("x","b"))""")
    }

    @Test
    fun `Not produces not with sub-traversal`() {
        assertThat(Not(PropEqual("name", "blocked")).toGremlin())
            .isEqualTo("""__.not(__.has("name","blocked"))""")
    }

    @Test
    fun `AndThen sequences two steps`() {
        assertThat(AndThen(PropEqual("name", "a"), PropNotNull("b")).toGremlin())
            .isEqualTo("""__.has("name","a").has("b")""")
    }

    @Test
    fun `HasLink produces where out-edge exists`() {
        assertThat(HasLink("onBoard").toGremlin())
            .isEqualTo("""__.where(__.out("onBoard_link"))""")
    }

    @Test
    fun `HasNoLink produces not out-edge`() {
        assertThat(HasNoLink("onBoard").toGremlin())
            .isEqualTo("""__.not(__.out("onBoard_link"))""")
    }

    @Test
    fun `HasLinkTo produces where out-edge with id check`() {
        assertThat(HasLinkTo("onBoard", RID.of(34, 4)).toGremlin())
            .isEqualTo("""__.where(__.out("onBoard_link").hasId(#34:4))""")
    }

    @Test
    fun `PropInRange produces has with range predicate`() {
        assertThat(PropInRange("value", 1, 5).toGremlin())
            .isEqualTo("""__.has("value",P.gte((int) 1).and(P.lte((int) 5)))""")
    }

    @Test
    fun `HasElement produces where unfold-and-match on collection`() {
        assertThat(HasElement("tags", "bug").toGremlin())
            .isEqualTo("""__.where(__.values("tags").unfold().is("bug"))""")
    }

    @Test
    fun `MatchStringProp substring produces toLower and contains check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Substring, "val", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.containing("val")))""")
    }

    @Test
    fun `MatchStringProp prefix produces toLower and startingWith check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Prefix, "pre", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.startingWith("pre")))""")
    }

    @Test
    fun `Dedup produces dedup`() {
        assertThat(Dedup.toGremlin()).isEqualTo("__.dedup()")
    }

    @Test
    fun `Limit produces limit`() {
        assertThat(Limit(10).toGremlin()).isEqualTo("__.limit(10L)")
    }

    @Test
    fun `Skip produces skip`() {
        assertThat(Skip(5).toGremlin()).isEqualTo("__.skip(5L)")
    }

    @Test
    fun `Tail produces tail`() {
        assertThat(Tail(5).toGremlin()).isEqualTo("__.tail(5L)")
    }

    @Test
    fun `HasLabel produces hasLabel`() {
        assertThat(HasLabel("Issue").toGremlin()).isEqualTo("""__.hasLabel("Issue")""")
    }

    @Test
    fun `OutLink produces out edge traversal`() {
        assertThat(OutLink("items").toGremlin()).isEqualTo("""__.out("items_link")""")
    }

    @Test
    fun `InLink produces in edge traversal`() {
        assertThat(InLink("items").toGremlin()).isEqualTo("""__.in("items_link")""")
    }

    @Test
    fun `Where wraps inner block in where step`() {
        assertThat(Where(PropEqual("name", "a")).toGremlin())
            .isEqualTo("""__.where(__.has("name","a"))""")
    }

    @Test
    fun `PropWithin produces has with within predicate`() {
        assertThat(PropWithin("status", listOf("a", "b")).toGremlin())
            .isEqualTo("""__.has("status",P.within(["a", "b"]))""")
    }

    @Test
    fun `IdEqual produces hasId`() {
        assertThat(IdEqual(RID.of(34, 4)).toGremlin())
            .isEqualTo("__.hasId(#34:4)")
    }

    @Test
    fun `IdWithin produces hasId with within predicate`() {
        assertThat(IdWithin(listOf(RID.of(34, 4), RID.of(34, 5))).toGremlin())
            .isEqualTo("__.hasId(P.within([#34:4, #34:5]))")
    }

    @Test
    fun `MatchStringProp equal case-sensitive produces has with eq predicate`() {
        assertThat(
            MatchStringProp("name", StringCompare.Equal, "John", isCollection = false, caseSensitive = true).toGremlin()
        ).isEqualTo("""__.has("name",P.eq("John"))""")
    }

    @Test
    fun `MatchStringProp equal case-insensitive produces toLower and eq check`() {
        assertThat(
            MatchStringProp("name", StringCompare.Equal, "John", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("name").toLower().is(P.eq("john")))""")
    }

    @Test
    fun `MatchStringProp suffix produces toLower and endingWith check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Suffix, "ue", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.endingWith("ue")))""")
    }

    @Test
    fun `MatchStringProp collection case-insensitive produces unfold toLower check`() {
        assertThat(
            MatchStringProp("tags", StringCompare.Substring, "val", isCollection = true, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("tags").unfold().toLower().is(TextP.containing("val")))""")
    }

    @Test
    fun `MatchStringProp collection case-sensitive produces unfold without toLower`() {
        assertThat(
            MatchStringProp("tags", StringCompare.Equal, "John", isCollection = true, caseSensitive = true).toGremlin()
        ).isEqualTo("""__.where(__.values("tags").unfold().is(P.eq("John")))""")
    }

    @Test
    fun `Reverse produces fold reverse unfold`() {
        assertThat(Reverse.toGremlin()).isEqualTo("__.fold().reverse().unfold()")
    }

    @Test
    fun `Sort by prop ascending produces order by nulls-last`() {
        assertThat(Sort(Sort.ByProp("name"), SortDirection.ASC).toGremlin())
            .isEqualTo("""__.order().by(__.values("name").count(),Order.desc).by(__.values("name").fold(),Order.asc)""")
    }

    @Test
    fun `Sort by prop descending produces order by nulls-last`() {
        assertThat(Sort(Sort.ByProp("name"), SortDirection.DESC).toGremlin())
            .isEqualTo("""__.order().by(__.values("name").count(),Order.desc).by(__.values("name").fold(),Order.desc)""")
    }

    @Test
    fun `Sort by linked prop ascending traverses edge then orders`() {
        assertThat(Sort(Sort.ByLinked("rel", "name"), SortDirection.ASC).toGremlin())
            .isEqualTo("""__.order().by(__.out("rel_link").values("name").count(),Order.desc).by(__.out("rel_link").values("name").fold(),Order.asc)""")
    }
}
