/**
 * Copyright 2006 - 2026 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jetbrains.exodus.entitystore.youtrackdb.query

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import com.jetbrains.youtrackdb.internal.core.db.record.record.RID
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinBlock
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinBlock.*
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery.ByIds
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery.FollowLink
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery.Labeled
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery.LinkDirection
import jetbrains.exodus.entitystore.youtrackdb.gremlin.GremlinQuery.SortBy
import jetbrains.exodus.entitystore.youtrackdb.gremlin.asYT
import org.apache.tinkerpop.gremlin.process.traversal.translator.GroovyTranslator
import org.apache.tinkerpop.gremlin.structure.util.empty.EmptyGraph
import org.junit.Test
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__ as Anon

/**
 * Tests that each GremlinBlock produces the expected Gremlin traversal.
 * This is the Gremlin-based analog of YTDBQueryTest from the graph-store branch,
 * which asserted the SQL strings generated by the SQL query builder.
 * Here we use GroovyTranslator to render the traversal bytecode as readable
 * Gremlin/Groovy strings and assert them.
 */
class GremlinQueryTest {

    private val translator = GroovyTranslator.of("__")
    private val queryTranslator = GroovyTranslator.of("g")
    private val gs = EmptyGraph.instance().traversal()

    private fun GremlinBlock.toGremlin(): String =
        translator.translate(traverse(Anon.start<Any>().asYT()).asAdmin().bytecode).script

    private fun GremlinQuery.toGremlin(): String =
        queryTranslator.translate(start(gs).asAdmin().bytecode).script

    @Test
    fun `All produces empty traversal`() {
        assertThat(All.toGremlin()).isEqualTo("__")
    }

    @Test
    fun `None produces discard`() {
        assertThat(None.toGremlin()).isEqualTo("__.discard()")
    }

    @Test
    fun `PropEqual produces has with value`() {
        assertThat(PropEqual("name", "John").toGremlin())
            .isEqualTo("""__.has("name","John")""")
    }

    @Test
    fun `PropNull produces hasNot`() {
        assertThat(PropNull("name").toGremlin())
            .isEqualTo("""__.hasNot("name")""")
    }

    @Test
    fun `PropNotNull produces has without value`() {
        assertThat(PropNotNull("prop").toGremlin())
            .isEqualTo("""__.has("prop")""")
    }

    @Test
    fun `Or produces or with two sub-traversals`() {
        assertThat(Or(PropEqual("name", "a"), PropEqual("name", "b")).toGremlin())
            .isEqualTo("""__.or(__.has("name","a"),__.has("name","b"))""")
    }

    @Test
    fun `And produces and with two sub-traversals`() {
        // Both operands are pure property filters (chainable) — O12 folds them directly.
        assertThat(And(PropEqual("name", "a"), PropEqual("x", "b")).toGremlin())
            .isEqualTo("""__.has("name","a").has("x","b")""")
    }

    @Test
    fun `Not produces not with sub-traversal`() {
        assertThat(Not(PropEqual("name", "blocked")).toGremlin())
            .isEqualTo("""__.not(__.has("name","blocked"))""")
    }

    @Test
    fun `AndThen sequences two steps`() {
        assertThat(AndThen(PropEqual("name", "a"), PropNotNull("b")).toGremlin())
            .isEqualTo("""__.has("name","a").has("b")""")
    }

    @Test
    fun `HasLink produces where out-edge exists`() {
        assertThat(HasLink("onBoard").toGremlin())
            .isEqualTo("""__.where(__.out("onBoard_link"))""")
    }

    @Test
    fun `HasNoLink produces not out-edge`() {
        assertThat(HasNoLink("onBoard").toGremlin())
            .isEqualTo("""__.not(__.out("onBoard_link"))""")
    }

    @Test
    fun `HasLinkTo produces where out-edge with id check`() {
        assertThat(HasLinkTo("onBoard", RID.of(34, 4)).toGremlin())
            .isEqualTo("""__.where(__.out("onBoard_link").hasId(#34:4))""")
    }

    @Test
    fun `PropInRange produces has with range predicate`() {
        assertThat(PropInRange("value", 1, 5).toGremlin())
            .isEqualTo("""__.has("value",P.gte((int) 1).and(P.lte((int) 5)))""")
    }

    @Test
    fun `HasElement produces where unfold-and-match on collection`() {
        assertThat(HasElement("tags", "bug").toGremlin())
            .isEqualTo("""__.where(__.values("tags").unfold().is("bug"))""")
    }

    @Test
    fun `MatchStringProp substring produces toLower and contains check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Substring, "val", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.containing("val")))""")
    }

    @Test
    fun `MatchStringProp prefix produces toLower and startingWith check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Prefix, "pre", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.startingWith("pre")))""")
    }

    @Test
    fun `Dedup produces dedup`() {
        assertThat(Dedup.toGremlin()).isEqualTo("__.dedup()")
    }

    @Test
    fun `Limit produces limit`() {
        assertThat(Limit(10).toGremlin()).isEqualTo("__.limit(10L)")
    }

    @Test
    fun `Skip produces skip`() {
        assertThat(Skip(5).toGremlin()).isEqualTo("__.skip(5L)")
    }

    @Test
    fun `Tail produces tail`() {
        assertThat(Tail(5).toGremlin()).isEqualTo("__.tail(5L)")
    }

    @Test
    fun `HasLabel produces hasLabel`() {
        assertThat(HasLabel("Issue").toGremlin()).isEqualTo("""__.hasLabel("Issue")""")
    }

    @Test
    fun `OutLink produces out edge traversal`() {
        assertThat(OutLink("items").toGremlin()).isEqualTo("""__.out("items_link")""")
    }

    @Test
    fun `InLink produces in edge traversal`() {
        assertThat(InLink("items").toGremlin()).isEqualTo("""__.in("items_link")""")
    }

    @Test
    fun `Where wraps inner block in where step`() {
        assertThat(Where(PropEqual("name", "a")).toGremlin())
            .isEqualTo("""__.where(__.has("name","a"))""")
    }

    @Test
    fun `PropWithin produces has with within predicate`() {
        assertThat(PropWithin("status", listOf("a", "b")).toGremlin())
            .isEqualTo("""__.has("status",P.within(["a", "b"]))""")
    }

    @Test
    fun `IdWithin produces hasId with within predicate`() {
        assertThat(IdWithin(listOf(RID.of(34, 4), RID.of(34, 5))).toGremlin())
            .isEqualTo("__.hasId(P.within([#34:4, #34:5]))")
    }

    @Test
    fun `ByIds builds direct g_V(ids), never a hasId class scan`() {
        // By-id lookups must put the ids ON the GraphStep (g.V(ids) → YTDB getElementsByIds, an O(1)
        // positional load), NOT g.V().hasId(...) which the planner runs as a FETCH FROM CLASS scan.
        val gremlin = ByIds(listOf(RID.of(34, 4), RID.of(34, 5))).toGremlin()
        assertThat(gremlin).isEqualTo("g.V(#34:4,#34:5)")
        assertThat(gremlin).doesNotContain("hasId")
    }

    @Test
    fun `ByIds with entityType keeps direct g_V(ids) plus a residual hasLabel`() {
        // entityType is only a residual class filter on the direct-load path; it must NOT turn the
        // query back into a hasId scan.
        val gremlin = ByIds(listOf(RID.of(34, 4)), "Issue").toGremlin()
        assertThat(gremlin).isEqualTo("""g.V(#34:4).hasLabel("Issue")""")
        assertThat(gremlin).doesNotContain("hasId")
    }

    @Test
    fun `ByIds over a transient (negative-position) RID still builds direct g_V(id)`() {
        // New/transient entities have a negative cluster position (e.g. #165:-3). The direct
        // getElementsByIds branch loads these from the in-tx record set, so the by-id form must hold
        // for negative RIDs exactly as for committed ones — no hasId fallback.
        val gremlin = ByIds(listOf(RID.of(165, -3))).toGremlin()
        assertThat(gremlin).isEqualTo("g.V(#165:-3)")
        assertThat(gremlin).doesNotContain("hasId")
    }

    @Test
    fun `ByIds then a property condition keeps direct g_V(ids), not a hasId scan`() {
        // Chaining a non-special block onto a ByIds must stay on the direct-load path. Collapsing it
        // to Where(IdWithin.andThen(...)) would emit g.V().hasId(within(...)).has(...) — a full vertex
        // scan filtered by id — which is exactly what by-id access exists to avoid.
        val gremlin = ByIds(listOf(RID.of(34, 4), RID.of(34, 5)))
            .then(PropEqual("name", "a"))
            .toGremlin()
        assertThat(gremlin).isEqualTo("""g.V(#34:4,#34:5).has("name","a")""")
        assertThat(gremlin).doesNotContain("hasId")
    }

    @Test
    fun `MatchStringProp equal case-sensitive produces has with eq predicate`() {
        assertThat(
            MatchStringProp("name", StringCompare.Equal, "John", isCollection = false, caseSensitive = true).toGremlin()
        ).isEqualTo("""__.has("name",P.eq("John"))""")
    }

    @Test
    fun `MatchStringProp equal case-insensitive produces toLower and eq check`() {
        assertThat(
            MatchStringProp("name", StringCompare.Equal, "John", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("name").toLower().is(P.eq("john")))""")
    }

    @Test
    fun `MatchStringProp suffix produces toLower and endingWith check`() {
        assertThat(
            MatchStringProp("prop", StringCompare.Suffix, "ue", isCollection = false, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("prop").toLower().is(TextP.endingWith("ue")))""")
    }

    @Test
    fun `MatchStringProp collection case-insensitive produces unfold toLower check`() {
        assertThat(
            MatchStringProp("tags", StringCompare.Substring, "val", isCollection = true, caseSensitive = false).toGremlin()
        ).isEqualTo("""__.where(__.values("tags").unfold().toLower().is(TextP.containing("val")))""")
    }

    @Test
    fun `MatchStringProp collection case-sensitive produces unfold without toLower`() {
        assertThat(
            MatchStringProp("tags", StringCompare.Equal, "John", isCollection = true, caseSensitive = true).toGremlin()
        ).isEqualTo("""__.where(__.values("tags").unfold().is(P.eq("John")))""")
    }

    @Test
    fun `Reverse produces fold reverse unfold`() {
        assertThat(Reverse.toGremlin()).isEqualTo("__.fold().reverse().unfold()")
    }

    @Test
    fun `Sort by prop ascending produces order by nulls-last`() {
        assertThat(Sort(Sort.ByProp("name"), SortDirection.ASC).toGremlin())
            .isEqualTo("""__.order().by(__.values("name").count(),Order.desc).by(__.values("name").fold(),Order.asc)""")
    }

    @Test
    fun `Sort by prop descending produces order by nulls-last`() {
        assertThat(Sort(Sort.ByProp("name"), SortDirection.DESC).toGremlin())
            .isEqualTo("""__.order().by(__.values("name").count(),Order.desc).by(__.values("name").fold(),Order.desc)""")
    }

    @Test
    fun `Sort by linked prop ascending traverses edge then orders`() {
        assertThat(Sort(Sort.ByLinked("rel", "name"), SortDirection.ASC).toGremlin())
            .isEqualTo("""__.order().by(__.out("rel_link").values("name").count(),Order.desc).by(__.out("rel_link").values("name").fold(),Order.asc)""")
    }

    // O3: SortBy passthrough in combineEfficient

    private fun issueCondition(prop: String, value: String): Labeled =
        Labeled(GremlinQuery.Where.of(PropEqual(prop, value)), "Issue")

    private val sortByName = Sort(Sort.ByProp("name"), SortDirection.ASC)
    private val sortByDate = Sort(Sort.ByProp("date"), SortDirection.ASC)

    private val sortByNameGremlin =
        """.order().by(__.values("name").count(),Order.desc).by(__.values("name").fold(),Order.asc)"""
    private val unionGremlin =
        """g.V().has("name",P.within(["a", "b"])).hasLabel("Issue")"""

    @Test
    fun `O3 - sorted union unsorted strips left sort and returns combined condition without sort`() {
        // Sort on one union operand does not define the sort of the union result.
        val result = SortBy(issueCondition("name", "a"), sortByName).union(issueCondition("name", "b"))
        assertThat(result.toGremlin()).isEqualTo(unionGremlin)
    }

    @Test
    fun `O3 - both sorted with same key union strips both sorts and returns combined condition without sort`() {
        val result = SortBy(issueCondition("name", "a"), sortByName)
            .union(SortBy(issueCondition("name", "b"), sortByName))
        assertThat(result.toGremlin()).isEqualTo(unionGremlin)
    }

    @Test
    fun `O3 - both sorted with different keys union strips both sorts and returns combined condition without sort`() {
        val result = SortBy(issueCondition("name", "a"), sortByName)
            .union(SortBy(issueCondition("name", "b"), sortByDate))
        assertThat(result.toGremlin()).isEqualTo(unionGremlin)
    }

    @Test
    fun `O3 - unsorted union sorted strips right sort and produces no sort wrapper`() {
        val result = issueCondition("name", "a")
            .union(SortBy(issueCondition("name", "b"), sortByName))
        assertThat(result.toGremlin()).isEqualTo(unionGremlin)
    }

    @Test
    fun `O3 - sorted intersect unsorted re-wraps combined condition preserving left sort`() {
        // intersect/difference: result is a filtered subset of `this`, so the sort is valid to preserve.
        val result = SortBy(issueCondition("name", "a"), sortByName).intersect(issueCondition("name", "b"))
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().has("name","a").has("name","b").hasLabel("Issue")$sortByNameGremlin""")
    }

    @Test
    fun `O3 - sorted difference unsorted re-wraps combined condition preserving left sort`() {
        val result = SortBy(issueCondition("name", "a"), sortByName).difference(issueCondition("name", "b"))
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().and(__.has("name","a"),__.not(__.has("name","b"))).hasLabel("Issue")$sortByNameGremlin""")
    }

    // O6: Labeled.of flattens nested Labeled wrappers

    @Test
    fun `O6 - Labeled of on already-labeled query flattens to single hasLabel`() {
        // then(HasLabel) on an existing Labeled query used to produce Labeled(Labeled(X, T), T),
        // which is structurally redundant and breaks extractCondition. Now it flattens.
        val inner = issueCondition("name", "a")
        val relabeled = GremlinQuery.Labeled.of(inner, "Issue")
        assertThat(relabeled.toGremlin()).isEqualTo("""g.V().has("name","a").hasLabel("Issue")""")
    }

    @Test
    fun `O6 - union of double-labeled queries combines correctly`() {
        // Without the fix, Labeled(Labeled(X, "Issue"), "Issue").union(Labeled(Y, "Issue")) would fall back
        // to UnionAll because extractCondition could not unwrap the nested Labeled.
        val a = GremlinQuery.Labeled.of(issueCondition("name", "a"), "Issue")
        val b = issueCondition("name", "b")
        assertThat(a.union(b).toGremlin())
            .isEqualTo("""g.V().has("name",P.within(["a", "b"])).hasLabel("Issue")""")
    }

    // O3 left branch — both operands are SortBy

    @Test
    fun `O3 - both sorted same key intersect strips right sort and preserves left sort`() {
        val result = SortBy(issueCondition("name", "a"), sortByName)
            .intersect(SortBy(issueCondition("name", "b"), sortByName))
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().has("name","a").has("name","b").hasLabel("Issue")$sortByNameGremlin""")
    }

    @Test
    fun `O3 - both sorted same key difference strips right sort and preserves left sort`() {
        val result = SortBy(issueCondition("name", "a"), sortByName)
            .difference(SortBy(issueCondition("name", "b"), sortByName))
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().and(__.has("name","a"),__.not(__.has("name","b"))).hasLabel("Issue")$sortByNameGremlin""")
    }

    // O3 right branch — this is NOT SortBy, other IS SortBy, for intersect/difference

    @Test
    fun `O3 - unsorted intersect sorted strips right sort`() {
        val result = issueCondition("name", "a")
            .intersect(SortBy(issueCondition("name", "b"), sortByName))
        // Right sort is stripped; no re-wrap since this is not SortBy
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().has("name","a").has("name","b").hasLabel("Issue")""")
    }

    @Test
    fun `O3 - unsorted difference sorted strips right sort`() {
        val result = issueCondition("name", "a")
            .difference(SortBy(issueCondition("name", "b"), sortByName))
        assertThat(result.toGremlin())
            .isEqualTo("""g.V().and(__.has("name","a"),__.not(__.has("name","b"))).hasLabel("Issue")""")
    }

    // O4 — FollowLink union shortcut

    @Test
    fun `O4 - union of in-link traversals with same link merges source queries`() {
        val boardA = Labeled(GremlinQuery.Where.of(PropEqual("name", "board1")), "Board")
        val boardB = Labeled(GremlinQuery.Where.of(PropEqual("name", "board2")), "Board")
        val issuesA = Labeled(FollowLink(boardA, LinkDirection.IN, "OnBoard"), "Issue")
        val issuesB = Labeled(FollowLink(boardB, LinkDirection.IN, "OnBoard"), "Issue")
        assertThat(issuesA.union(issuesB).toGremlin())
            .isEqualTo("""g.V().has("name",P.within(["board1", "board2"])).hasLabel("Board").in("OnBoard_link").hasLabel("Issue").dedup()""")
    }

    // Mismatched labels — falls back to UnionAll

    @Test
    fun `mismatched labels cause union to fall back to UnionAll with dedup`() {
        val issue = issueCondition("name", "a")
        val board = Labeled(GremlinQuery.Where.of(PropEqual("name", "b")), "Board")
        assertThat(issue.union(board).toGremlin())
            .isEqualTo("""g.union(__.V().has("name","a").hasLabel("Issue"),__.V().has("name","b").hasLabel("Board")).dedup()""")
    }

    // ByIds combination

    @Test
    fun `ByIds union ByIds produces distinct id union`() {
        val rid1 = RID.of(34, 1)
        val rid2 = RID.of(34, 2)
        val result = ByIds(listOf(rid1)).union(ByIds(listOf(rid2)))
        assertThat(result).isInstanceOf(ByIds::class.java)
        assertThat((result as ByIds).ids).containsExactly(rid1, rid2)
    }

    @Test
    fun `ByIds union ByIds deduplicates shared ids`() {
        val rid1 = RID.of(34, 1)
        val rid2 = RID.of(34, 2)
        val result = ByIds(listOf(rid1, rid2)).union(ByIds(listOf(rid2)))
        assertThat(result).isInstanceOf(ByIds::class.java)
        assertThat((result as ByIds).ids).containsExactly(rid1, rid2)
    }

    @Test
    fun `ByIds intersect ByIds produces id intersection`() {
        val rid1 = RID.of(34, 1)
        val rid2 = RID.of(34, 2)
        val rid3 = RID.of(34, 3)
        val result = ByIds(listOf(rid1, rid2)).intersect(ByIds(listOf(rid2, rid3)))
        assertThat(result).isInstanceOf(ByIds::class.java)
        assertThat((result as ByIds).ids).containsExactly(rid2)
    }

    @Test
    fun `ByIds difference ByIds produces id difference`() {
        val rid1 = RID.of(34, 1)
        val rid2 = RID.of(34, 2)
        val result = ByIds(listOf(rid1, rid2)).difference(ByIds(listOf(rid2)))
        assertThat(result).isInstanceOf(ByIds::class.java)
        assertThat((result as ByIds).ids).containsExactly(rid1)
    }

    // Pure conditions (no label) and mixed labeled/unlabeled

    @Test
    fun `unlabeled conditions union combines without hasLabel`() {
        val a = GremlinQuery.Where.of(PropEqual("name", "a"))
        val b = GremlinQuery.Where.of(PropEqual("name", "b"))
        assertThat(a.union(b).toGremlin())
            .isEqualTo("""g.V().has("name",P.within(["a", "b"]))""")
    }

    @Test
    fun `labeled union unlabeled inherits the label`() {
        val labeled = issueCondition("name", "a")
        val unlabeled = GremlinQuery.Where.of(PropEqual("name", "b"))
        assertThat(labeled.union(unlabeled).toGremlin())
            .isEqualTo("""g.V().has("name",P.within(["a", "b"])).hasLabel("Issue")""")
    }

    @Test
    fun `unlabeled union labeled inherits the label`() {
        val unlabeled = GremlinQuery.Where.of(PropEqual("name", "a"))
        val labeled = issueCondition("name", "b")
        // label = thisLabel ?: otherLabel — label comes from the right side when left is unlabeled
        assertThat(unlabeled.union(labeled).toGremlin())
            .isEqualTo("""g.V().has("name",P.within(["a", "b"])).hasLabel("Issue")""")
    }

    // O2 — identity shortcuts in combineBlocks

    @Test
    fun `O2 - intersect of identical conditions returns the same condition`() {
        val a = issueCondition("name", "a")
        assertThat(a.intersect(a).toGremlin())
            .isEqualTo("""g.V().has("name","a").hasLabel("Issue")""")
    }

    @Test
    fun `O2 - union of identical conditions returns the same condition`() {
        val a = issueCondition("name", "a")
        assertThat(a.union(a).toGremlin())
            .isEqualTo("""g.V().has("name","a").hasLabel("Issue")""")
    }

    @Test
    fun `O2 - difference of identical conditions returns None`() {
        val a = issueCondition("name", "a")
        // Difference.combineBlocks(c, c) → None → Labeled(Where(None), "Issue")
        // None renders as discard(); the hasLabel is dead code but preserved by the implementation
        assertThat(a.difference(a).toGremlin())
            .isEqualTo("""g.V().discard().hasLabel("Issue")""")
    }

    // O16 — Chained O7 fusion: Labeled(AndThen(FollowLink, cond1)) OP cond2

    private val engSrc     = Labeled(GremlinQuery.Where.of(PropEqual("key", "ENG")), "Project")
    private val engIssues  = Labeled(FollowLink(engSrc, LinkDirection.IN, "project"), "Issue")
    // o7Fused = Labeled(AndThen(FollowLink(ENG), PropEqual("status","open")), "Issue") — via O7
    private val o7Fused    = engIssues.intersect(issueCondition("status", "open"))

    @Test
    fun `O16 - O7-fused intersect condition extends traversal chain`() {
        // O7 already fused FollowLink+open into a single chain; O16 appends critical to it.
        val result = o7Fused.intersect(issueCondition("priority", "critical"))
        assertThat(result.toGremlin()).isEqualTo(
            """g.V().has("key","ENG").hasLabel("Project").in("project_link")""" +
            """.has("status","open").has("priority","critical").hasLabel("Issue")"""
        )
    }

    @Test
    fun `O16 - O7-fused difference condition extends traversal chain with not`() {
        // Difference: Not(PropEqual("status","resolved")) appended via AndThen.
        val result = o7Fused.difference(issueCondition("status", "resolved"))
        assertThat(result.toGremlin()).isEqualTo(
            """g.V().has("key","ENG").hasLabel("Project").in("project_link")""" +
            """.has("status","open").not(__.has("status","resolved")).hasLabel("Issue")"""
        )
    }

    @Test
    fun `O16 - O7-fused difference non-chainable condition extends chain`() {
        // Non-chainable (HasLink) difference: Not(HasLink) appended — same pattern as Q82.
        val hasAssignee = Labeled(GremlinQuery.Where.of(HasLink("assignee")), "Issue")
        val result = o7Fused.difference(hasAssignee)
        assertThat(result.toGremlin()).isEqualTo(
            """g.V().has("key","ENG").hasLabel("Project").in("project_link")""" +
            """.has("status","open").not(__.out("assignee_link")).hasLabel("Issue")"""
        )
    }

    @Test
    fun `O16 - union of O7-fused with condition falls back to UnionAll`() {
        // O16 only applies to intersect and difference; union cannot be expressed as a chain extension.
        val result = o7Fused.union(issueCondition("priority", "critical"))
        assertThat(result).isInstanceOf(GremlinQuery.Order::class.java)
    }

    // O21 — allOf(T) ∩ Q rewrites to Q.then(HasLabel(T)) instead of a full-scan Aggregate

    private fun allOf(label: String): Labeled = Labeled(GremlinQuery.Where.of(All), label)

    private val boardCond = Labeled(GremlinQuery.Where.of(PropEqual("name", "b")), "Board")
    private val issuesOnBoard = Labeled(FollowLink(boardCond, LinkDirection.IN, "OnBoard"), "Issue")
    private val issuesOnBoardGremlin =
        """g.V().has("name","b").hasLabel("Board").in("OnBoard_link").hasLabel("Issue")"""

    @Test
    fun `O21 - allOf(T) intersect FollowLink appends hasLabel instead of Aggregate`() {
        val result = allOf("Issue").intersect(issuesOnBoard)
        assertThat(result).isNotInstanceOf(GremlinQuery.Aggregate::class.java)
        assertThat(result.toGremlin()).isEqualTo(issuesOnBoardGremlin)
    }

    @Test
    fun `O21 - FollowLink intersect allOf(T) appends hasLabel instead of Aggregate`() {
        // Symmetric: the FollowLink is `this`, allOf is `other`.
        val result = issuesOnBoard.intersect(allOf("Issue"))
        assertThat(result).isNotInstanceOf(GremlinQuery.Aggregate::class.java)
        assertThat(result.toGremlin()).isEqualTo(issuesOnBoardGremlin)
    }

    @Test
    fun `O21 - allOf(T) intersect unlabeled FollowLink adds the label`() {
        // Bare (unlabeled) FollowLink: the type filter materialises as a trailing hasLabel.
        val bareLink = FollowLink(boardCond, LinkDirection.IN, "OnBoard")
        val result = allOf("Issue").intersect(bareLink)
        assertThat(result).isNotInstanceOf(GremlinQuery.Aggregate::class.java)
        assertThat(result.toGremlin()).isEqualTo(issuesOnBoardGremlin)
    }

    @Test
    fun `O21 - bare Where(All) intersect query is pure identity`() {
        // Untyped All ⇒ no hasLabel appended; the result is the other operand verbatim.
        val q = issuesOnBoard
        assertThat(GremlinQuery.all.intersect(q).toGremlin()).isEqualTo(q.toGremlin())
        assertThat(q.intersect(GremlinQuery.all).toGremlin()).isEqualTo(q.toGremlin())
    }

    @Test
    fun `O21 - allOf(T) intersect allOf(T) collapses to allOf(T)`() {
        val result = allOf("Issue").intersect(allOf("Issue"))
        assertThat(result.toGremlin()).isEqualTo("""g.V().hasLabel("Issue")""")
    }

    @Test
    fun `O21 - allOf(T) intersect condition is left to the generic combiner`() {
        // Condition has an extractable block, so O21 does NOT fire — combineBlocks(All, cond) = cond.
        val result = allOf("Issue").intersect(issueCondition("status", "open"))
        assertThat(result.toGremlin()).isEqualTo("""g.V().has("status","open").hasLabel("Issue")""")
    }

    @Test
    fun `O21 - allOf(T) intersect OUT-FollowLink over ByIds rewrites in both operand orders`() {
        // Mirrors the YouTrack permissions shape:
        //   Aggregate(Labeled(Where(All), "JPUser"), FollowLink(ByIds, OUT, "viewers"))
        // O21 must rewrite it to drive from the bounded id set rather than scanning every JPUser,
        // and must do so regardless of which side the allOf operand is on.
        val ids = ByIds(listOf(RID.of(40, 1), RID.of(40, 2)))
        val viewers = FollowLink(ids, LinkDirection.OUT, "viewers")

        listOf(
            allOf("JPUser").intersect(viewers),  // allOf on the left  → O21 branch 1
            viewers.intersect(allOf("JPUser")),   // operands switched   → O21 branch 2 (symmetric)
        ).forEach { result ->
            assertThat(result).isNotInstanceOf(GremlinQuery.Aggregate::class.java)
            assertThat(result).isInstanceOf(Labeled::class.java)
            val labeled = result as Labeled
            assertThat(labeled.label).isEqualTo("JPUser")
            // The exact FollowLink is preserved as the driving traversal; only a hasLabel is added.
            assertThat(labeled.inner).isEqualTo(viewers)
        }
    }

    @Test
    fun `O21 - allOf(T) intersect Slice applies the type filter after the page`() {
        // Paging case: the type filter must be appended AFTER the skip, matching the old Aggregate
        // (which also filters by type after the page is computed). The surviving page is identical.
        val bareLink = FollowLink(boardCond, LinkDirection.IN, "OnBoard")
        val sliced = bareLink.then(Skip(1))   // Slice(bareLink, Skip(1))
        val result = allOf("Issue").intersect(sliced)
        assertThat(result).isNotInstanceOf(GremlinQuery.Aggregate::class.java)
        assertThat(result.toGremlin()).isEqualTo(
            """g.V().has("name","b").hasLabel("Board").in("OnBoard_link").skip(1L).hasLabel("Issue")"""
        )
    }

    @Test
    fun `O21 - allOf(T) does not pre-empt O_B for Aggregate intersect allOf`() {
        // O21 is placed after O_B precisely so O_B wins here: O_B recognises that the Aggregate's
        // left branch is already labeled T and drops the redundant hasLabel entirely, rather than
        // O21 appending an AndThen(Aggregate, hasLabel). Guards the placement-after-O_B invariant.
        val aggr = issueCondition("status", "open")
            .intersect(Labeled(GremlinQuery.Where.of(PropEqual("key", "ENG")), "Project"))
        assertThat(aggr).isInstanceOf(GremlinQuery.Aggregate::class.java)

        // Both orders resolve to the bare Aggregate, not an O21 rewrite.
        assertThat(aggr.intersect(allOf("Issue"))).isEqualTo(aggr)
        assertThat(allOf("Issue").intersect(aggr)).isEqualTo(aggr)
    }

    // --- O21 correctness investigation: OR-collapse (concern #1) and per-step safety (concern #2) ---

    @Test
    fun `O21 - allOf(T) intersect FollowLink of a DIFFERENT label stays Aggregate`() {
        // Concern #1, the OR-collapse hazard: hasLabel(U).hasLabel(T) on consecutive steps is merged
        // by InlineFilterStrategy into one multi-predicate HasStep that YTDBHasLabelStep evaluates as
        // OR (the O19 defect). O21 must never create that shape. The label-mismatch guard above O21
        // ensures it: when the other operand has a non-null label U != T, combineEfficient returns
        // null *before* O21 → Aggregate, so no hasLabel(T) is appended onto an operand ending in
        // hasLabel(U). Verified both orders.
        val projectsLink = Labeled(FollowLink(boardCond, LinkDirection.IN, "OnBoard"), "Project")
        assertThat(allOf("Issue").intersect(projectsLink)).isInstanceOf(GremlinQuery.Aggregate::class.java)
        assertThat(projectsLink.intersect(allOf("Issue"))).isInstanceOf(GremlinQuery.Aggregate::class.java)
    }

    @Test
    fun `O21 - no rewrite ever emits two consecutive hasLabel steps`() {
        // Concern #1, structural proof: across every O21-eligible shape, the appended hasLabel(T) is
        // either flattened (operand already labeled T) or separated from any pre-existing distinct
        // hasLabel by a link / skip / where step. So the merge-able `hasLabel(A).hasLabel(B)` adjacency
        // is never produced. GroovyTranslator renders bytecode pre-strategy, so adjacency (if any)
        // would appear literally in the script.
        val adjacentHasLabel = Regex("""hasLabel\([^)]*\)\.hasLabel\(""")
        val ids = ByIds(listOf(RID.of(40, 1)))
        val rewrites = listOf(
            allOf("Issue").intersect(FollowLink(boardCond, LinkDirection.IN, "OnBoard")),  // bare FL
            FollowLink(boardCond, LinkDirection.OUT, "viewers").intersect(allOf("Issue")),  // symmetric
            allOf("Issue").intersect(issuesOnBoard),                                         // operand already labeled Issue (flattens)
            allOf("Issue").intersect(FollowLink(ids, LinkDirection.OUT, "viewers")),         // production shape
            allOf("Issue").intersect(FollowLink(boardCond, LinkDirection.IN, "OnBoard").then(Skip(1))), // Slice
        )
        rewrites.forEach { q ->
            assertWithMessage("rewrite produced consecutive hasLabel: %s", q.toGremlin())
                .that(adjacentHasLabel.containsMatchIn(q.toGremlin())).isFalse()
        }
    }
}
